# Docs: https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md

gui:
  returnImmediately: true
  expandFocusedSidePanel: true
  # Source: https://github.com/fmind/theme/blob/main/themes/lazydocker/fmind.yml
  theme:
    activeBorderColor: ["#174ea6", bold]
    inactiveBorderColor: ["#595d62"]
    selectedLineBgColor: ["#d2e3fc"]
    optionsTextColor: ["#174ea6"]
