# Docs: https://antigravity.google/docs/cli/reference/
# No native completion generator in the reviewed CLI; refresh against agy --help.
complete -c agy -f
complete -c agy -n __fish_use_subcommand -l add-dir -r -d 'Add a directory to the workspace (repeatable) (default [])'
complete -c agy -n __fish_use_subcommand -l agent -r -d 'Agent for the current CLI session'
complete -c agy -n __fish_use_subcommand -s c -d 'Short alias for --continue'
complete -c agy -n __fish_use_subcommand -l continue -d 'Continue the most recent conversation'
complete -c agy -n __fish_use_subcommand -l conversation -r -d 'Resume a previous conversation by ID'
complete -c agy -n __fish_use_subcommand -l dangerously-skip-permissions -d 'Auto-approve all tool permission requests without prompting'
complete -c agy -n __fish_use_subcommand -l disable-slash-commands -d 'Disable slash command and skill expansion in print mode'
complete -c agy -n __fish_use_subcommand -l effort -x -a 'low medium high max' -d 'Reasoning effort for the current CLI session'
complete -c agy -n __fish_use_subcommand -s i -r -d 'Short alias for --prompt-interactive'
complete -c agy -n __fish_use_subcommand -l input-format -r -d 'Input format for print mode (text, stream-json). stream-json reads one NDJSON message per line from stdin and runs a turn for each; it requires --output-format stream-json (default text)'
complete -c agy -n __fish_use_subcommand -l json-schema -r -d 'Optional JSON schema string or path to a schema file to enforce structured output (for stream-json, only applicable to the final result)'
complete -c agy -n __fish_use_subcommand -l log-file -r -d 'Override CLI log file path'
complete -c agy -n __fish_use_subcommand -l mode -r -d 'Set the agent execution mode for this session (accept-edits, plan)'
complete -c agy -n __fish_use_subcommand -l model -r -d 'Model for the current CLI session'
complete -c agy -n __fish_use_subcommand -l new-project -d 'Create a new project for this session'
complete -c agy -n __fish_use_subcommand -l output-format -r -d 'Output format for print mode (text, json, stream-json) (default text)'
complete -c agy -n __fish_use_subcommand -s p -r -d 'Short alias for --print'
complete -c agy -n __fish_use_subcommand -l print -r -d 'Run a single prompt non-interactively and print the response'
complete -c agy -n __fish_use_subcommand -l print-timeout -r -d 'Optional print-mode time limit; 0 waits until completion (default 0s)'
complete -c agy -n __fish_use_subcommand -l project -r -d 'Project ID or project name for the current CLI session'
complete -c agy -n __fish_use_subcommand -l prompt -r -d 'Alias for --print'
complete -c agy -n __fish_use_subcommand -l prompt-interactive -r -d 'Run an initial prompt interactively and continue the session'
complete -c agy -n __fish_use_subcommand -l remote-control -d 'Create a remote connection for the CLI session on startup'
complete -c agy -n __fish_use_subcommand -l sandbox -d 'Run in a sandbox with terminal restrictions enabled'
complete -c agy -n '__fish_use_subcommand' -a agent -d 'List available agents'
complete -c agy -n '__fish_use_subcommand' -a agents -d 'List available agents'
complete -c agy -n '__fish_use_subcommand' -a changelog -d 'Show changelog and release notes'
complete -c agy -n '__fish_use_subcommand' -a help -d 'Show help for subcommands'
complete -c agy -n '__fish_use_subcommand' -a install -d 'Configure environment paths and shell settings'
complete -c agy -n '__fish_use_subcommand' -a mcp -d 'Manage MCP servers (add, remove, list, enable, disable)'
complete -c agy -n '__fish_use_subcommand' -a mic-serve -d 'Serve the local microphone to a CLI on another host'
complete -c agy -n '__fish_use_subcommand' -a models -d 'List available models'
complete -c agy -n '__fish_use_subcommand' -a plugin -d 'Manage plugins (install, uninstall, list, enable, disable)'
complete -c agy -n '__fish_use_subcommand' -a plugins -d 'Alias for plugin'
complete -c agy -n '__fish_use_subcommand' -a remote-control -d 'Manage the remote-control background daemon (start, status, stop)'
complete -c agy -n '__fish_use_subcommand' -a update -d 'Update CLI'
complete -c agy -n '__fish_seen_subcommand_from remote-control' -a 'start status stop'
complete -c agy -n '__fish_seen_subcommand_from mcp' -a 'add remove list enable disable'
complete -c agy -n '__fish_seen_subcommand_from plugin' -a 'list import install uninstall enable disable validate link help'
complete -c agy -n '__fish_seen_subcommand_from plugins' -a 'list import install uninstall enable disable validate link help'
complete -c agy -n '__fish_seen_subcommand_from remote-control; and __fish_seen_subcommand_from start' -l name -r -d 'Remote machine name'
complete -c agy -n '__fish_seen_subcommand_from remote-control; and __fish_seen_subcommand_from start' -l session -d 'Run until logout'
complete -c agy -n '__fish_seen_subcommand_from mic-serve' -l addr -r -d 'Microphone listener address (keep on loopback)'
