# Docs: https://antigravity.google/docs/cli/reference/
# agy 1.2.3 has no native completion generator; refresh against agy --help.
complete -c agy -f
complete -c agy -l add-dir -r -d 'Add a directory to the workspace (repeatable) (default [])'
complete -c agy -l agent -r -d 'Agent for the current CLI session'
complete -c agy -s c -d 'Short alias for --continue'
complete -c agy -l continue -d 'Continue the most recent conversation'
complete -c agy -l conversation -r -d 'Resume a previous conversation by ID'
complete -c agy -l dangerously-skip-permissions -d 'Auto-approve all tool permission requests without prompting'
complete -c agy -l disable-slash-commands -d 'Disable slash command and skill expansion in print mode'
complete -c agy -l effort -r -d 'Reasoning effort for the current CLI session (low|medium|high)'
complete -c agy -s i -r -d 'Short alias for --prompt-interactive'
complete -c agy -l input-format -r -d 'Input format for print mode (text, stream-json). stream-json reads one NDJSON message per line from stdin and runs a turn for each; it requires --output-format stream-json (default text)'
complete -c agy -l json-schema -r -d 'Optional JSON schema string or path to a schema file to enforce structured output (for stream-json, only applicable to the final result)'
complete -c agy -l log-file -r -d 'Override CLI log file path'
complete -c agy -l mode -r -d 'Set the agent execution mode for this session (accept-edits, plan)'
complete -c agy -l model -r -d 'Model for the current CLI session'
complete -c agy -l new-project -d 'Create a new project for this session'
complete -c agy -l output-format -r -d 'Output format for print mode (text, json, stream-json) (default text)'
complete -c agy -s p -r -d 'Short alias for --print'
complete -c agy -l print -r -d 'Run a single prompt non-interactively and print the response'
complete -c agy -l print-timeout -r -d 'Timeout for print mode wait (default 5m0s)'
complete -c agy -l project -r -d 'Project ID or project name for the current CLI session'
complete -c agy -l prompt -r -d 'Alias for --print'
complete -c agy -l prompt-interactive -r -d 'Run an initial prompt interactively and continue the session'
complete -c agy -l sandbox -d 'Run in a sandbox with terminal restrictions enabled'
complete -c agy -n '__fish_use_subcommand' -a agent -d 'List available agents'
complete -c agy -n '__fish_use_subcommand' -a agents -d 'List available agents'
complete -c agy -n '__fish_use_subcommand' -a changelog -d 'Show changelog and release notes'
complete -c agy -n '__fish_use_subcommand' -a help -d 'Show help for subcommands'
complete -c agy -n '__fish_use_subcommand' -a install -d 'Configure environment paths and shell settings'
complete -c agy -n '__fish_use_subcommand' -a mcp -d 'Manage MCP servers (add, remove, list, enable, disable)'
complete -c agy -n '__fish_use_subcommand' -a mic-serve -d 'Serve the local microphone to a CLI on another host'
complete -c agy -n '__fish_use_subcommand' -a models -d 'List available models'
complete -c agy -n '__fish_use_subcommand' -a plugin -d 'Manage plugins (install, uninstall, list, enable, disable)'
complete -c agy -n '__fish_use_subcommand' -a plugins -d 'Alias for plugin'
complete -c agy -n '__fish_use_subcommand' -a remote-control -d 'Manage the remote-control background daemon (start, status, stop)'
complete -c agy -n '__fish_use_subcommand' -a update -d 'Update CLI'
complete -c agy -n '__fish_seen_subcommand_from remote-control' -a 'start status stop'
complete -c agy -n '__fish_seen_subcommand_from mcp' -a 'add remove list enable disable'
complete -c agy -n '__fish_seen_subcommand_from plugin' -a 'list import install uninstall enable disable validate link help'
complete -c agy -n '__fish_seen_subcommand_from plugins' -a 'list import install uninstall enable disable validate link help'
complete -c agy -n '__fish_seen_subcommand_from remote-control; and __fish_seen_subcommand_from start' -l name -r -d 'Remote machine name'
complete -c agy -n '__fish_seen_subcommand_from remote-control; and __fish_seen_subcommand_from start' -l session -d 'Run until logout'
