# :schema https://mise.jdx.dev/schema/mise.json
# Docs: https://mise.jdx.dev/configuration.html

[tools]
helm = "latest" # Package manager for Kubernetes charts
k3d = "latest" # Run lightweight k3s Kubernetes clusters in Docker
k9s = "latest" # Terminal UI for viewing Kubernetes clusters
kind = "latest" # Kubernetes IN Docker cluster manager
kube-linter = "latest" # Static analysis linter for Kubernetes YAML/Helm
kubeconform = "latest" # Kubernetes manifest schema validator
kubectl = "latest" # Command-line tool to control Kubernetes clusters
kubectx = "latest" # Fast switcher between Kubernetes cluster contexts
kubens = "latest" # Switch between Kubernetes namespaces
kustomize = "latest" # Customizes raw Kubernetes YAML configurations
stern = "latest" # Multi-pod and multi-container log tailing for Kubernetes
